from typing import Any
from pydantic import BaseModel


class SendCmd(BaseModel):
    cmdstr: str
    url: str
    id: int
    data: Any = None


class ScrOrder:
    START = "START"
    END = "END"
    UPDATE = "UPDATE"
    UPDATE_ACT_ALL = "UPDATE_ACT_ALL"
    AUTO_UPDATE_ACT_ALL = "AUTO_UPDATE_ACT_ALL"
    DB_ORGANIZE_DAYS = "DB_ORGANIZE_DAYS"
    DB_ORGANIZE_SYNC = "DB_ORGANIZE_SYNC"
    DB_ORGANIZE_LOG_2DAYS_CLEANER = "DB_ORGANIZE_LOG_2DAYS_CLEANER"
    DB_ORGANIZE_LOG_CLEANER = "DB_ORGANIZE_LOG_CLEANER"
    UPDATE_ONLINE_STORE_POSTAGE = "UPDATE_ONLINE_STORE_POSTAGE"
    UPDATE_API_PRICE = "UPDATE_API_PRICE"
    ORDERLIST = (
        START,
        END,
        UPDATE,
        UPDATE_ACT_ALL,
        AUTO_UPDATE_ACT_ALL,
        DB_ORGANIZE_DAYS,
        DB_ORGANIZE_SYNC,
        DB_ORGANIZE_LOG_2DAYS_CLEANER,
        DB_ORGANIZE_LOG_CLEANER,
        UPDATE_ONLINE_STORE_POSTAGE,
        UPDATE_API_PRICE,
    )
