version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: postgres-nginx
        ports:
            - 80:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
    fastapi:
        build: kakakuscraping/
        ports:
            - 8000:8000
        init: true
        volumes:
            - ./DATA/tempdata/log:/app/tempdata/log
            - ./DATA/tempdata/html:/app/tempdata/html
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: posgre134
        volumes:
            - ./DATA/db:/var/lib/postgresql/data
            - ./postgres-init:/docker-entrypoint-initdb.d


        
